#!/usr/bin/env python3
"""Baseline writer tool for eval_matrix summary.json output (D-11-07 / BASE-01).

Reads a completed eval-matrix summary.json and writes/updates
``configs/eval_baselines/<scenario_id>.json`` cells.

Refusal rules (D-10-03):
    1. Cells with ``n_scored < n_requested`` are REFUSED — a partial run must
       never become committed empirical record.
    2. Scenarios with ``baseline_eligible: false`` (D-10-09 quarantine) have
       ALL their provider cells refused — a quarantined scenario must never be
       regenerated by this tool.

Provenance:
    Every written cell is stamped with ``generated_at`` (UTC ISO-8601 compact)
    and ``generated_by = "scripts/write_baselines.py"``.

_observations carry-forward:
    If a prior baseline file exists for a scenario, any ``_observations``
    annotation on an existing provider cell is carried forward into the
    rewritten cell.

Usage::

    poetry run python scripts/write_baselines.py eval_reports/{ts}/summary.json
    make write-baselines SUMMARY=eval_reports/{ts}/summary.json RUNS=5

Exit codes (matching check_eval_gates.py / check_baselines_fresh.py):
    0 = all eligible cells written successfully
    1 = one or more cells REFUSED (D-10-03: n_scored < n_requested or
        D-10-09: baseline_eligible=False)
    2 = infrastructure failure (missing summary.json, malformed JSON)
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from collections.abc import Sequence
from pathlib import Path

# No top-level LLM SDK imports — this script is stdlib-only.


# ---------------------------------------------------------------------------
# JSON loading helpers
# ---------------------------------------------------------------------------


def _load_json_file(path_str: str, label: str) -> dict:
    """Load and return a JSON file as a Python dict.

    Raises OSError on missing file, ValueError on parse/shape failure.
    """
    p = Path(path_str)
    if not p.exists():
        raise OSError(f"{label} not found: {path_str}")
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"could not parse {label} at {path_str}: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{label} at {path_str} is not a JSON object")
    return data


# ---------------------------------------------------------------------------
# Argparse
# ---------------------------------------------------------------------------


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    """Parse argv."""
    parser = argparse.ArgumentParser(
        prog="write_baselines",
        description=(
            "Write baseline JSONs from a completed eval-matrix summary.json (D-11-07). "
            "Refuses partial cells (n_scored < n_requested, D-10-03) and quarantined "
            "scenarios (baseline_eligible=False, D-10-09). Stamps generated_at / "
            "generated_by and carries forward prior _observations."
        ),
    )
    parser.add_argument(
        "summary",
        help="Path to summary.json from an eval_matrix run.",
    )
    parser.add_argument(
        "--n-requested",
        type=int,
        default=5,
        help="Expected run count per cell (RUNS=N at eval time). Default: 5.",
    )
    parser.add_argument(
        "--baselines-dir",
        default="configs/eval_baselines",
        help="Directory holding per-scenario baseline JSONs (default: configs/eval_baselines).",
    )
    return parser.parse_args(list(argv))


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def _utc_now_stamp() -> str:
    """Return a compact UTC timestamp in ``YYYY-MM-DDTHH-MM-SSZ`` format."""
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H-%M-%SZ")  # noqa: DTZ003


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point. Returns the script's exit code.

    Exit codes:
        0 = all eligible cells written successfully
        1 = one or more cells REFUSED (partial or quarantined)
        2 = infrastructure failure (missing summary.json, malformed JSON)
    """
    args = _parse_args(argv if argv is not None else sys.argv[1:])

    try:
        summary = _load_json_file(args.summary, "summary.json")
    except (OSError, ValueError) as exc:
        sys.stderr.write(f"write_baselines: {exc}\n")
        return 2

    n_requested: int = args.n_requested
    baselines_dir = Path(args.baselines_dir)

    # Track all refused cells; return 1 if any were refused.
    refused: list[str] = []

    for scenario_id, scenario_block in summary.get("scenarios", {}).items():
        baseline_eligible: bool = scenario_block.get("baseline_eligible", True)
        providers_block: dict = scenario_block.get("providers", {})

        # Load prior baseline (for _observations carry-forward and cell merge).
        baseline_path = baselines_dir / f"{scenario_id}.json"
        prior_payload: dict = {}
        if baseline_path.exists():
            try:
                prior_payload = json.loads(baseline_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                # Prior file unreadable — treat as absent; no carry-forward.
                prior_payload = {}

        prior_providers: dict = prior_payload.get("providers", {})

        # Build the updated providers block for this scenario (starts from
        # the prior file so unrelated provider cells are preserved).
        updated_providers: dict = dict(prior_providers)

        for provider_key, cell in providers_block.items():
            n_scored: int = cell.get("n_scored", 0)

            # Refusal rule 1: quarantined scenario (D-10-09).
            if not baseline_eligible:
                sys.stderr.write(
                    f"write_baselines: REFUSED — scenario {scenario_id!r} "
                    f"has baseline_eligible=False (D-10-09 quarantine); "
                    f"skipping provider cell {provider_key!r}\n"
                )
                refused.append(f"{scenario_id}/{provider_key}")
                continue

            # Refusal rule 2: partial cell (D-10-03).
            if n_scored < n_requested:
                sys.stderr.write(
                    f"write_baselines: REFUSED — {scenario_id}/{provider_key} "
                    f"n_scored={n_scored} < n_requested={n_requested} (D-10-03)\n"
                )
                refused.append(f"{scenario_id}/{provider_key}")
                continue

            # Build the new provider cell.
            baseline_cell: dict = {
                "scorers": cell["scorers"],
                "generated_at": _utc_now_stamp(),
                "generated_by": "scripts/write_baselines.py",
            }

            # Carry forward _observations from the prior on-disk baseline.
            prior_obs = prior_providers.get(provider_key, {}).get("_observations")
            if prior_obs:
                baseline_cell["_observations"] = prior_obs

            updated_providers[provider_key] = baseline_cell

        # If the scenario was fully quarantined (all cells refused for eligibility),
        # do not write or modify the baseline file.
        if not baseline_eligible:
            continue

        # Build the full baseline payload for this scenario.
        # Preserve top-level fields from the prior file that are not auto-generated
        # (e.g. closure_check_confirmed, scenario_id if already present).
        payload: dict = {k: v for k, v in prior_payload.items() if k not in ("providers",)}
        payload["scenario_id"] = scenario_id
        payload["generated_at"] = _utc_now_stamp()
        payload["generated_by"] = "scripts/write_baselines.py"
        payload["providers"] = updated_providers

        # WR-02: write ONLY if at least one summary cell was actually accepted.
        # When every cell of this scenario was refused (e.g. a partial run),
        # the file must stay byte-identical — rewriting it would bump the
        # top-level generated_at/generated_by provenance stamp over stale
        # numbers AND satisfy the check_baselines_fresh.py staleness gate
        # without any actual data refresh.
        accepted = [pk for pk in providers_block if f"{scenario_id}/{pk}" not in refused]
        if accepted:
            baselines_dir.mkdir(parents=True, exist_ok=True)
            baseline_path.write_text(
                json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
            )

    if refused:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
